title : Cours
copyright : Par Jessica Licence ATC
collections:
  legumes:
    output: true
  autres:
    output: true
  products:
    output: true
---
title : Bonzour les zens
baseurl : /flatfiles
---
