title : Cours
copyright : Par Jessica Licence ATC
collections:
  legumes:
    output: true
  autres:
    output: true
  products:
    output: true
---
title : Salut tout le monde
baseurl : /flatfiles
---
